### ISSUE TITLE
Why not use dnf config-manager --add-repo ?

### ISSUE THREAD

**Issue by atodorov** [osbuild/gitlab-ci-terraform#5]
in prepareScript instead of writing out the repo file. 

Asked by @Gundersanne in https://github.com/osbuild/gitlab-ci-terraform/pull/4#pullrequestreview-665304641 and I don't have an answer here.

**Comment by Gundersanne** [comment]
Was just a small observation. If there's not much to gain I wouldn't bother switching over.
